### PR TITLE
Referring to Issue #119

### PR DESCRIPTION
**Pull request by ChintzRuparel**
The colour schema on the pie chart isn't that accurate in nature.  Hence a new colour schema has been provided.

The issue with the old colour schema was that beyond a certain number of values the thing got looped and the same colours were used over and over again. Hence making a colour schema which is accurate was of utmost importance and making this thing usable to everyone in a very simpler way. 

Note to devs - Do lemme know what do think about it

### CODE REVIEW

**Comment by tipsy** [comment]
Thanks @ChintzRuparel - do you have a screenshot?

**Comment by ChintzRuparel** [comment]
Hey @tipsy, 

As I have edited the file on the GitHub editor I haven't created a build locally. If u merge this on GitHub and apply changes in a different branch I feel the changes can be applied. 

Thanks, 
@ChintzRuparel

**Comment by iProdigy** [comment]
Screenshot: https://i.imgur.com/iQqp4Sp.png

I think these colors are too vibrant/bright

**Comment by tipsy** [comment]
> I think these colors are too vibrant/bright

Agree!

**Comment by ChintzRuparel** [comment]
Created new pull request #123

**Comment by ChintzRuparel** [comment]
Created new pull request #123

**Pull request closed without merging**
