### PR TITLE
README Formatting

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-609926?style=for-the-badge&logoColor=white&logo=GitHub
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-D81939?style=for-the-badge&logoColor=white&logo=GitLFS
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-73398D?style=for-the-badge&logoColor=white&logo=AskUbuntu

[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- ***[Disable Unused Widgets][Widgets]***:

  - `Packages`

  - `Releases`

  <br>

- ***[Disable Unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`

  - `Wiki`

<br>
<br>

## ![Badge Changes]

- General formatting / spacing

- Moved building / usage into dedicated files

- Added quicklinks

- Added license badge

- Referenced links

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/profile-summary-for-github

### CODE REVIEW

**Comment by tipsy** [comment]
I'm having some trouble visualizing this, but I will merge it and have a look :)

**Comment by tipsy** [comment]
I don't know if I prefer it, but I will let it stay like this for a while at least. Thank you !

**Comment by Bhumi-X** [comment]
Screenshot_20250618-143802 Telegram

**Comment by Bhumi-X** [comment]
BACK TO BACK JEET MUBARAK

**Pull request merged**
